### ISSUE TITLE
The Backup destination does not exist.

### ISSUE THREAD

**Issue by OscarVanL** [skleeschulte/basic-to-sharepoint-auth-http-proxy#4]
Hi,

I've had this setup for some weeks and it's been fine. Recently the backups and backup integrity checks keep failing because "Exception occurred while backing up data. (The backup destination does not exist)".

What is strange is that in Hyper Backup's 'Target' GUI it has a green status symbol saying "On-line". 

If I go to 'Backup Explorer' I can see and download multiple version histories of the same file, so it's clear the connection to OneDrive Sharepoint is valid.

I can see that I've used 3573/5000GB on my OneDrive account, so there's still room to spare.

I'm unsure why the connection to Sharepoint seems to work and yet the backups keep failing for connection issues. 

Any ideas why this may happen?

**Comment by skleeschulte** [comment]
Hi, sorry for the late response. Is this still an issue? If so, first step I suggest is to [turn on debug-logging](https://github.com/skleeschulte/basic-to-sharepoint-auth-http-proxy#logging--debugging) and have a look at the log output.

**Comment by OscarVanL** [comment]
I just ended up buying a second Synology for backups, so I'll close the issue as it's no longer relevant. But thank you :)
